---
title: "Introducing R"
subtitle: "... the greatest thing since sliced bread!"
author: "Dan Negrey"
output:
    ioslides_presentation:
        widescreen: TRUE
        transition: slower
        fig_width: 10
        css: 
         - ./css/body-slide.css
         - ./css/code-chunks.css
         - ./css/code-inline.css
         - ./css/plots.css
         - ./css/slide-background.css
         - ./css/slide-notes.css
         - ./css/title-slide.css
        includes: 
            before_body: ./html/title.html
---

`r htmltools::includeCSS("./main.css")`

```{r child="./slides/data-days/slide.Rmd"}
```

```{r child="./slides/what-is-R/slide.Rmd"}
```

```{r child="./slides/R-project/slide.Rmd"}
```

```{r child="./slides/download-R/slide.Rmd"}
```

```{r child="./slides/the-R-interface/slide.Rmd"}
```

```{r child="./slides/how-does-R-work/slide.Rmd"}
```

```{r child="./slides/rstudio/slide.Rmd"}
```

```{r child="./slides/packages-dplyr/slide.Rmd"}
```

```{r child="./slides/packages-ggplot2/slide.Rmd"}
```

```{r child="./slides/packages-rmarkdown/slide.Rmd"}
```

```{r child="./slides/packages-leaflet/slide.Rmd"}
```

```{r child="./slides/packages-DT/slide.Rmd"}
```

```{r child="./slides/packages-dygraphs/slide.Rmd"}
```

```{r child="./slides/packages-RODBC/slide.Rmd"}
```

```{r child="./slides/packages-XLConnect/slide.Rmd"}
```

```{r child="./slides/thank-you/slide.Rmd"}
```
